log:
    level: "DEBUG"
    format: "%(levelname)s: %(message)s"
eye:
    grayscale:
        weight_r: 0.299
        weight_g: 0.587
        weight_b: 0.114
    binarize:
        thresh_pupil_rel: 3.5
        thresh_iris_rel: 1.35
    morpho_pupil:
        hole_size_max: 500
        disk_radius: 15
    morpho_iris:
        hole_size_max: 500
        disk_radius: 20
    center:
        method: "centroid"
    radius_pupil:
        method: "area"
    radius_iris:
        method: "profile_horizontal"
        sigma: 3
        radius_rel_min: 1.2
        radius_rel_max: 3.0
    unwrap:
        res_theta: 128
        res_r: 32
    daugman:
        gabor:
            length: 35
            sigma: 4
            frequency: 0.12
plot:
    masks:
        color_pupil: [1.0, 0.0, 0.0]
        color_iris:  [0.0, 0.0, 1.0]
    center:
        radius: 2
        color: "yellow"
    radius_pupil:
        color: "yellow"
    radius_iris:
        color: "yellow"
