log:
    level: "DEBUG"
    format: "%(levelname)s: %(message)s"
eye:
    grayscale:
        weight_r: 0.299
        weight_g: 0.587
        weight_b: 0.114
    binarize:
        thresh_pupil_rel: 3.5
        thresh_iris_rel: 1.5
    morpho:
        hole_size_max: 500
        disk_radius: 20
    center:
        method: "centroid"
plot:
    masks:
        color_pupil: [1.0, 0.0, 0.0]
        color_iris:  [0.0, 0.0, 1.0]
    center:
        radius: 2
        color: "yellow"
