# generated by datamodel-codegen:
#   filename:  config.yaml
#   timestamp: 2026-04-23T20:56:35+00:00

from __future__ import annotations

from pydantic import BaseModel


class ConfigLog(BaseModel):
    level: str
    format: str


class ConfigEyeGrayscale(BaseModel):
    weight_r: float
    weight_g: float
    weight_b: float


class ConfigEyeBinarize(BaseModel):
    thresh_pupil_rel: float
    thresh_iris_rel: float


class ConfigEyeMorpho(BaseModel):
    hole_size_max: int
    disk_radius: int


class ConfigEyeCenter(BaseModel):
    method: str


class ConfigEye(BaseModel):
    grayscale: ConfigEyeGrayscale
    binarize: ConfigEyeBinarize
    morpho: ConfigEyeMorpho
    center: ConfigEyeCenter


class ConfigPlotMasks(BaseModel):
    color_pupil: list[float]
    color_iris: list[float]


class ConfigPlotCenter(BaseModel):
    radius: int
    color: str


class ConfigPlot(BaseModel):
    masks: ConfigPlotMasks
    center: ConfigPlotCenter


class Config(BaseModel):
    log: ConfigLog
    eye: ConfigEye
    plot: ConfigPlot
