# generated by datamodel-codegen:
#   filename:  config.yaml
#   timestamp: 2026-04-24T19:09:38+00:00

from __future__ import annotations

from pydantic import BaseModel


class ConfigLog(BaseModel):
    level: str
    format: str


class ConfigEyeGrayscale(BaseModel):
    weight_r: float
    weight_g: float
    weight_b: float


class ConfigEyeBinarize(BaseModel):
    thresh_pupil_rel: float
    thresh_iris_rel: float


class ConfigEyeMorphoPupil(BaseModel):
    hole_size_max: int
    disk_radius: int


class ConfigEyeMorphoIris(BaseModel):
    hole_size_max: int
    disk_radius: int


class ConfigEyeCenter(BaseModel):
    method: str


class ConfigEyeRadiusPupil(BaseModel):
    method: str


class ConfigEyeRadiusIris(BaseModel):
    method: str
    sigma: int
    radius_rel_min: float
    radius_rel_max: float


class ConfigEyeUnwrap(BaseModel):
    res_theta: int
    res_r: int


class ConfigEyeDaugmanGabor(BaseModel):
    length: int
    sigma: int
    frequency: float


class ConfigEyeDaugman(BaseModel):
    gabor: ConfigEyeDaugmanGabor


class ConfigEye(BaseModel):
    grayscale: ConfigEyeGrayscale
    binarize: ConfigEyeBinarize
    morpho_pupil: ConfigEyeMorphoPupil
    morpho_iris: ConfigEyeMorphoIris
    center: ConfigEyeCenter
    radius_pupil: ConfigEyeRadiusPupil
    radius_iris: ConfigEyeRadiusIris
    unwrap: ConfigEyeUnwrap
    daugman: ConfigEyeDaugman


class ConfigPlotMasks(BaseModel):
    color_pupil: list[float]
    color_iris: list[float]


class ConfigPlotCenter(BaseModel):
    radius: int
    color: str


class ConfigPlotRadiusPupil(BaseModel):
    color: str


class ConfigPlotRadiusIris(BaseModel):
    color: str


class ConfigPlot(BaseModel):
    masks: ConfigPlotMasks
    center: ConfigPlotCenter
    radius_pupil: ConfigPlotRadiusPupil
    radius_iris: ConfigPlotRadiusIris


class Config(BaseModel):
    log: ConfigLog
    eye: ConfigEye
    plot: ConfigPlot
