# generated by datamodel-codegen:
#   filename:  config.yaml
#   timestamp: 2026-04-23T22:03:45+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ConfigLog(BaseModel):
    level: str
    format: str


class ConfigEyeGrayscale(BaseModel):
    weight_r: float
    weight_g: float
    weight_b: float


class ConfigEyeBinarize(BaseModel):
    thresh_pupil_rel: float
    thresh_iris_rel: float


class ConfigEyeMorpho(BaseModel):
    hole_size_max: int
    disk_radius: int


class ConfigEyeCenter(BaseModel):
    method: str


class ConfigEyeRadiusPupil(BaseModel):
    method: str


class ConfigEyeRadiusIris(BaseModel):
    method: str


class ConfigEye(BaseModel):
    grayscale: ConfigEyeGrayscale
    binarize: ConfigEyeBinarize
    morpho: ConfigEyeMorpho
    center: ConfigEyeCenter
    radius_pupil: ConfigEyeRadiusPupil = Field(..., alias='radius-pupil')
    radius_iris: ConfigEyeRadiusIris = Field(..., alias='radius-iris')


class ConfigPlotMasks(BaseModel):
    color_pupil: list[float]
    color_iris: list[float]


class ConfigPlotCenter(BaseModel):
    radius: int
    color: str


class ConfigPlotRadiusPupil(BaseModel):
    color: str


class ConfigPlotRadiusIris(BaseModel):
    color: str


class ConfigPlot(BaseModel):
    masks: ConfigPlotMasks
    center: ConfigPlotCenter
    radius_pupil: ConfigPlotRadiusPupil = Field(..., alias='radius-pupil')
    radius_iris: ConfigPlotRadiusIris = Field(..., alias='radius-iris')


class Config(BaseModel):
    log: ConfigLog
    eye: ConfigEye
    plot: ConfigPlot
